DROP DATABASE THEATRES;

Create DATABASE theatres;

use theatres;

create table shows(
    show_id int PRIMARY KEY auto_increment,
    movie_name VARCHAR(50) not null,
    time time not null,
    screen_name VARCHAR(50) not null, 
    UNIQUE(show_id,movie_name)
);

create table seat_info(
    show_id int not null,
    seat_type VARCHAR(50),
    price double not null,
    seat_count int not null,
    PRIMARY KEY(SHOW_ID, SEAT_TYPE),
    FOREIGN KEY(show_id) REFERENCES shows(show_id)
);

-- CREATE TABLE seats(
--     show_id int not null,
--     seat_type VARCHAR(50) NOT NULL,
--     seat_no int NOT NULL,
--     status int NOT NULL,
--     PRIMARY KEY(SHOW_ID, SEAT_TYPE, SEAT_NO),
--     FOREIGN KEY(show_id) REFERENCES shows(show_id) 
-- );

CREATE TABLE BOOKINGS (
    ticket_id INT PRIMARY KEY auto_increment,
    SHOW_ID INT NOT NULL,
    TICKET_STATUS VARCHAR(50) NOT NULL DEFAULT "PAID",
    TICKET_PRICE DOUBLE NOT NULL,
    REFUNDED_PRICE DOUBLE NOT NULL DEFAULT 0,
    FOREIGN KEY(ticket_id) REFERENCES SHOWS(SHOW_ID)
);

CREATE TABLE BOOKED_SEATS(
    TICKET_ID INT NOT NULL,
    SEAT_TYPE VARCHAR(50) NOT NULL,
    SEAT_NO INT NOT NULL,
    SEAT_STATUS VARCHAR(50) NOT NULL DEFAULT "RESERVED",
    FOREIGN KEY(TICKET_ID) REFERENCES BOOKINGS(TICKET_ID),
    PRIMARY KEY(TICKET_ID, SEAT_TYPE, SEAT_NO)
);


-- POPULATING DATA

INSERT INTO SHOWS(movie_name,time,screen_name) VALUES("AVATAR","05:50:00","A");
INSERT INTO SHOWS(movie_name,time,screen_name) VALUES("ARMAGEDDON","12:30:00","A");
INSERT INTO SHOWS(movie_name,time,screen_name) VALUES("ALLADIN","06:30:00","A");
INSERT INTO SHOWS(movie_name,time,screen_name) VALUES("JUMANJI","10:30:00","A");

INSERT INTO SEAT_INFO(SHOW_ID,SEAT_TYPE,PRICE,seat_count) VALUES("1","PLATINUM",300,16);
INSERT INTO SEAT_INFO(SHOW_ID,SEAT_TYPE,PRICE,seat_count) VALUES("1","GOLD",200,24);
INSERT INTO SEAT_INFO(SHOW_ID,SEAT_TYPE,PRICE,seat_count) VALUES("1","SILVER",100,32);

INSERT INTO SEAT_INFO(SHOW_ID,SEAT_TYPE,PRICE,seat_count) VALUES("2","PLATINUM",300,16);
INSERT INTO SEAT_INFO(SHOW_ID,SEAT_TYPE,PRICE,seat_count) VALUES("2","GOLD",200,24);
INSERT INTO SEAT_INFO(SHOW_ID,SEAT_TYPE,PRICE,seat_count) VALUES("2","SILVER",100,32);

INSERT INTO SEAT_INFO(SHOW_ID,SEAT_TYPE,PRICE,seat_count) VALUES("3","PLATINUM",300,16);
INSERT INTO SEAT_INFO(SHOW_ID,SEAT_TYPE,PRICE,seat_count) VALUES("3","GOLD",200,24);
INSERT INTO SEAT_INFO(SHOW_ID,SEAT_TYPE,PRICE,seat_count) VALUES("3","SILVER",100,32);

INSERT INTO SEAT_INFO(SHOW_ID,SEAT_TYPE,PRICE,seat_count) VALUES("4","PLATINUM",300,16);
INSERT INTO SEAT_INFO(SHOW_ID,SEAT_TYPE,PRICE,seat_count) VALUES("4","GOLD",200,24);
INSERT INTO SEAT_INFO(SHOW_ID,SEAT_TYPE,PRICE,seat_count) VALUES("4","SILVER",100,32);

INSERT INTO BOOKINGS(SHOW_ID,TICKET_PRICE) VALUES(1,500);

INSERT INTO BOOKED_SEATS(TICKET_ID,SEAT_TYPE,SEAT_NO) VALUES(1,"SILVER",1);
INSERT INTO BOOKED_SEATS(TICKET_ID,SEAT_TYPE,SEAT_NO) VALUES(1,"SILVER",2); 
INSERT INTO BOOKED_SEATS(TICKET_ID,SEAT_TYPE,SEAT_NO) VALUES(1,"SILVER",3);
INSERT INTO BOOKED_SEATS(TICKET_ID,SEAT_TYPE,SEAT_NO) VALUES(1,"SILVER",4);
INSERT INTO BOOKED_SEATS(TICKET_ID,SEAT_TYPE,SEAT_NO) VALUES(1,"SILVER",5);

INSERT INTO BOOKINGS(SHOW_ID,TICKET_PRICE) VALUES(1,400);

INSERT INTO BOOKED_SEATS(TICKET_ID,SEAT_TYPE,SEAT_NO) VALUES(1,"GOLD",1);
INSERT INTO BOOKED_SEATS(TICKET_ID,SEAT_TYPE,SEAT_NO) VALUES(1,"GOLD",2); 

SELECT BOOKED_SEATS.SEAT_TYPE, BOOKINGS.TICKET_ID, BOOKED_SEATS.SEAT_NO FROM BOOKINGS, BOOKED_SEATS WHERE BOOKINGS.SHOW_ID = 1 AND SEAT_TYPE = 'GOLD' AND SEAT_STATUS = 'RESERVED';

SELECT * FROM SHOWS WHERE SHOW_ID = 1;

